import 'package:conduit_vt/conduit_vt.dart';
import 'package:flutter/material.dart';

enum AppPalette {
  catppuccin,
  tokyoNight,
  dracula,
  nord,
  gruvbox,
  solarized,
  oneDark,
  rosePine,
  everforest,
  monokai,
  ayuDark,
  kanagawa,
  nightOwl,
  palenight,
  synthwave,
  githubDark,
}

/// To add a palette: add a value to [AppPalette], then add its `PaletteSpec`
/// case to [AppPaletteDetails._spec]. The analyzer will flag the missing case.
/// Only the values here are authored per palette; lighter shades and the
/// `*For(Brightness)` helpers in [AppPaletteDetails] are derived from them.
@immutable
class PaletteSpec {
  const PaletteSpec({
    required this.label,
    required this.caption,
    required this.accent,
    required this.accentSecondary,
    required this.canvas,
    required this.panel,
    required this.panelElevated,
    required this.hairline,
    required this.border,
    required this.foreground,
    required this.mutedForeground,
    required this.subtleForeground,
    required this.success,
    required this.warning,
    required this.danger,
    required this.canvasLight,
    required this.foregroundLight,
    required this.terminalDark,
    required this.terminalLight,
  });

  final String label;
  final String caption;
  final Color accent;
  final Color accentSecondary;
  final Color canvas;
  final Color panel;
  final Color panelElevated;
  final Color hairline;
  final Color border;
  final Color foreground;
  final Color mutedForeground;
  final Color subtleForeground;
  final Color success;
  final Color warning;
  final Color danger;
  final Color canvasLight;
  final Color foregroundLight;
  final TerminalTheme terminalDark;
  final TerminalTheme terminalLight;
}

/// Shared light terminal theme for palettes that do not author their own.
const TerminalTheme _lightFallbackTerminal = TerminalTheme(
  cursor: Color(0xFF383A42),
  selection: Color(0x66C8CCD4),
  foreground: Color(0xFF383A42),
  background: Color(0xFFECEFF4),
  black: Color(0xFF4F5666),
  red: Color(0xFFE45649),
  green: Color(0xFF50A14F),
  yellow: Color(0xFFC18401),
  blue: Color(0xFF4078F2),
  magenta: Color(0xFFA626A4),
  cyan: Color(0xFF0184BC),
  white: Color(0xFFA0A1A7),
  brightBlack: Color(0xFF696C77),
  brightRed: Color(0xFFE45649),
  brightGreen: Color(0xFF50A14F),
  brightYellow: Color(0xFFC18401),
  brightBlue: Color(0xFF4078F2),
  brightMagenta: Color(0xFFA626A4),
  brightCyan: Color(0xFF0184BC),
  brightWhite: Color(0xFF383A42),
  searchHitBackground: Color(0xFFE5C07B),
  searchHitBackgroundCurrent: Color(0xFF61AFEF),
  searchHitForeground: Color(0xFFECEFF4),
);

extension AppPaletteDetails on AppPalette {
  String get label => _spec.label;
  String get caption => _spec.caption;

  Color get seed => accent;

  Color get accent => _spec.accent;
  Color get accentSecondary => _spec.accentSecondary;
  Color get canvas => _spec.canvas;
  Color get panel => _spec.panel;
  Color get panelElevated => _spec.panelElevated;
  Color get hairline => _spec.hairline;
  Color get border => _spec.border;
  Color get foreground => _spec.foreground;
  Color get mutedForeground => _spec.mutedForeground;
  Color get subtleForeground => _spec.subtleForeground;
  Color get success => _spec.success;
  Color get warning => _spec.warning;
  Color get danger => _spec.danger;

  Color get accentSoft => accent.withValues(alpha: 0.16);
  Color get accentGlow => accent.withValues(alpha: 0.08);
  Color get accentOnDark => Color.lerp(accent, Colors.black, 0.55)!;

  Color get canvasLight => _spec.canvasLight;
  Color get panelLight => Color.lerp(canvasLight, Colors.white, 0.55)!;
  Color get panelElevatedLight => Colors.white;
  Color get hairlineLight => Color.lerp(canvasLight, accent, 0.06)!;
  Color get borderLight => Color.lerp(canvasLight, accent, 0.16)!;
  Color get foregroundLight => _spec.foregroundLight;
  Color get mutedForegroundLight =>
      Color.lerp(foregroundLight, canvasLight, 0.35)!;
  Color get subtleForegroundLight =>
      Color.lerp(foregroundLight, canvasLight, 0.55)!;

  Color canvasFor(Brightness b) => b == Brightness.dark ? canvas : canvasLight;
  Color panelFor(Brightness b) => b == Brightness.dark ? panel : panelLight;
  Color panelElevatedFor(Brightness b) =>
      b == Brightness.dark ? panelElevated : panelElevatedLight;
  Color hairlineFor(Brightness b) =>
      b == Brightness.dark ? hairline : hairlineLight;
  Color borderFor(Brightness b) => b == Brightness.dark ? border : borderLight;
  Color foregroundFor(Brightness b) =>
      b == Brightness.dark ? foreground : foregroundLight;
  Color mutedForegroundFor(Brightness b) =>
      b == Brightness.dark ? mutedForeground : mutedForegroundLight;
  Color subtleForegroundFor(Brightness b) =>
      b == Brightness.dark ? subtleForeground : subtleForegroundLight;

  Color terminalBackgroundFor(Brightness b) => canvasFor(b);
  Color terminalPanelFor(Brightness b) => panelFor(b);
  Color terminalForegroundFor(Brightness b) => foregroundFor(b);
  Color terminalMutedForegroundFor(Brightness b) => mutedForegroundFor(b);
  Color terminalBorderFor(Brightness b) => hairlineFor(b);

  TerminalTheme terminalThemeFor(Brightness brightness) =>
      brightness == Brightness.dark ? terminalTheme : lightTerminalTheme;

  TerminalTheme get terminalTheme => _spec.terminalDark;
  TerminalTheme get lightTerminalTheme => _spec.terminalLight;

  PaletteSpec get _spec => switch (this) {
    AppPalette.catppuccin => const PaletteSpec(
      label: 'Catppuccin',
      caption: 'Mocha, calm and polished',
      accent: Color(0xFFCBA6F7),
      accentSecondary: Color(0xFFF5C2E7),
      canvas: Color(0xFF0F0F18),
      panel: Color(0xFF181825),
      panelElevated: Color(0xFF1E1E2E),
      hairline: Color(0xFF26273A),
      border: Color(0xFF313244),
      foreground: Color(0xFFCDD6F4),
      mutedForeground: Color(0xFF9399B2),
      subtleForeground: Color(0xFF6C7086),
      success: Color(0xFFA6E3A1),
      warning: Color(0xFFF9E2AF),
      danger: Color(0xFFF38BA8),
      canvasLight: Color(0xFFEFF1F5),
      foregroundLight: Color(0xFF1E1E2E),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFF5E0DC),
        selection: Color(0x6645475A),
        foreground: Color(0xFFCDD6F4),
        background: Color(0xFF0F0F18),
        black: Color(0xFF45475A),
        red: Color(0xFFF38BA8),
        green: Color(0xFFA6E3A1),
        yellow: Color(0xFFF9E2AF),
        blue: Color(0xFF89B4FA),
        magenta: Color(0xFFF5C2E7),
        cyan: Color(0xFF94E2D5),
        white: Color(0xFFBAC2DE),
        brightBlack: Color(0xFF585B70),
        brightRed: Color(0xFFF38BA8),
        brightGreen: Color(0xFFA6E3A1),
        brightYellow: Color(0xFFF9E2AF),
        brightBlue: Color(0xFF89B4FA),
        brightMagenta: Color(0xFFF5C2E7),
        brightCyan: Color(0xFF94E2D5),
        brightWhite: Color(0xFFA6ADC8),
        searchHitBackground: Color(0xFFF9E2AF),
        searchHitBackgroundCurrent: Color(0xFFA6E3A1),
        searchHitForeground: Color(0xFF0F0F18),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF4C4F69),
        selection: Color(0x66ACB0BE),
        foreground: Color(0xFF4C4F69),
        background: Color(0xFFEFF1F5),
        black: Color(0xFF5C5F77),
        red: Color(0xFFD20F39),
        green: Color(0xFF40A02B),
        yellow: Color(0xFFDF8E1D),
        blue: Color(0xFF1E66F5),
        magenta: Color(0xFFEA76CB),
        cyan: Color(0xFF179299),
        white: Color(0xFFACB0BE),
        brightBlack: Color(0xFF6C6F85),
        brightRed: Color(0xFFD20F39),
        brightGreen: Color(0xFF40A02B),
        brightYellow: Color(0xFFDF8E1D),
        brightBlue: Color(0xFF1E66F5),
        brightMagenta: Color(0xFFEA76CB),
        brightCyan: Color(0xFF179299),
        brightWhite: Color(0xFFBCC0CC),
        searchHitBackground: Color(0xFFDF8E1D),
        searchHitBackgroundCurrent: Color(0xFF40A02B),
        searchHitForeground: Color(0xFFEFF1F5),
      ),
    ),
    AppPalette.tokyoNight => const PaletteSpec(
      label: 'Tokyo Night',
      caption: 'Deep blue IDE focus',
      accent: Color(0xFF7AA2F7),
      accentSecondary: Color(0xFFBB9AF7),
      canvas: Color(0xFF0A0E1A),
      panel: Color(0xFF131826),
      panelElevated: Color(0xFF1A2138),
      hairline: Color(0xFF1F2945),
      border: Color(0xFF2C3858),
      foreground: Color(0xFFC0CAF5),
      mutedForeground: Color(0xFF7E89B5),
      subtleForeground: Color(0xFF565F89),
      success: Color(0xFF9ECE6A),
      warning: Color(0xFFE0AF68),
      danger: Color(0xFFF7768E),
      canvasLight: Color(0xFFE9ECF5),
      foregroundLight: Color(0xFF111A2D),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFC0CAF5),
        selection: Color(0x66565F89),
        foreground: Color(0xFFC0CAF5),
        background: Color(0xFF0A0E1A),
        black: Color(0xFF15161E),
        red: Color(0xFFF7768E),
        green: Color(0xFF9ECE6A),
        yellow: Color(0xFFE0AF68),
        blue: Color(0xFF7AA2F7),
        magenta: Color(0xFFBB9AF7),
        cyan: Color(0xFF7DCFFF),
        white: Color(0xFFA9B1D6),
        brightBlack: Color(0xFF414868),
        brightRed: Color(0xFFF7768E),
        brightGreen: Color(0xFF9ECE6A),
        brightYellow: Color(0xFFE0AF68),
        brightBlue: Color(0xFF7AA2F7),
        brightMagenta: Color(0xFFBB9AF7),
        brightCyan: Color(0xFF7DCFFF),
        brightWhite: Color(0xFFC0CAF5),
        searchHitBackground: Color(0xFFE0AF68),
        searchHitBackgroundCurrent: Color(0xFF7AA2F7),
        searchHitForeground: Color(0xFF0A0E1A),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF3760BF),
        selection: Color(0x66899AD6),
        foreground: Color(0xFF3760BF),
        background: Color(0xFFE9ECF5),
        black: Color(0xFF6172B0),
        red: Color(0xFFF52A65),
        green: Color(0xFF587539),
        yellow: Color(0xFF8C6C3E),
        blue: Color(0xFF2E7DE9),
        magenta: Color(0xFF9854F1),
        cyan: Color(0xFF007197),
        white: Color(0xFFA1A6C5),
        brightBlack: Color(0xFFA1A6C5),
        brightRed: Color(0xFFF52A65),
        brightGreen: Color(0xFF587539),
        brightYellow: Color(0xFF8C6C3E),
        brightBlue: Color(0xFF2E7DE9),
        brightMagenta: Color(0xFF9854F1),
        brightCyan: Color(0xFF007197),
        brightWhite: Color(0xFF3760BF),
        searchHitBackground: Color(0xFF8C6C3E),
        searchHitBackgroundCurrent: Color(0xFF2E7DE9),
        searchHitForeground: Color(0xFFE9ECF5),
      ),
    ),
    AppPalette.dracula => const PaletteSpec(
      label: 'Dracula',
      caption: 'High-contrast neon classic',
      accent: Color(0xFFBD93F9),
      accentSecondary: Color(0xFFFF79C6),
      canvas: Color(0xFF15161E),
      panel: Color(0xFF1F2029),
      panelElevated: Color(0xFF282A36),
      hairline: Color(0xFF353746),
      border: Color(0xFF44475A),
      foreground: Color(0xFFF8F8F2),
      mutedForeground: Color(0xFF9A9CB0),
      subtleForeground: Color(0xFF6272A4),
      success: Color(0xFF50FA7B),
      warning: Color(0xFFF1FA8C),
      danger: Color(0xFFFF5555),
      canvasLight: Color(0xFFF7F7F4),
      foregroundLight: Color(0xFF1F2029),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFF8F8F2),
        selection: Color(0x66565F89),
        foreground: Color(0xFFF8F8F2),
        background: Color(0xFF15161E),
        black: Color(0xFF21222C),
        red: Color(0xFFFF5555),
        green: Color(0xFF50FA7B),
        yellow: Color(0xFFF1FA8C),
        blue: Color(0xFFBD93F9),
        magenta: Color(0xFFFF79C6),
        cyan: Color(0xFF8BE9FD),
        white: Color(0xFFF8F8F2),
        brightBlack: Color(0xFF6272A4),
        brightRed: Color(0xFFFF6E6E),
        brightGreen: Color(0xFF69FF94),
        brightYellow: Color(0xFFFFFFA5),
        brightBlue: Color(0xFFD6ACFF),
        brightMagenta: Color(0xFFFF92DF),
        brightCyan: Color(0xFFA4FFFF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFF1FA8C),
        searchHitBackgroundCurrent: Color(0xFF50FA7B),
        searchHitForeground: Color(0xFF15161E),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF282A36),
        selection: Color(0x66C7C8D1),
        foreground: Color(0xFF282A36),
        background: Color(0xFFF7F7F4),
        black: Color(0xFF44475A),
        red: Color(0xFFFF5555),
        green: Color(0xFF1E9F4A),
        yellow: Color(0xFF9A7B00),
        blue: Color(0xFF6250C8),
        magenta: Color(0xFFC7448F),
        cyan: Color(0xFF087C8F),
        white: Color(0xFFD7D7D2),
        brightBlack: Color(0xFF6272A4),
        brightRed: Color(0xFFD73838),
        brightGreen: Color(0xFF188A3E),
        brightYellow: Color(0xFF806600),
        brightBlue: Color(0xFF4E3FB3),
        brightMagenta: Color(0xFFA93478),
        brightCyan: Color(0xFF066B7B),
        brightWhite: Color(0xFF282A36),
        searchHitBackground: Color(0xFFF1C40F),
        searchHitBackgroundCurrent: Color(0xFF50FA7B),
        searchHitForeground: Color(0xFF282A36),
      ),
    ),
    AppPalette.nord => const PaletteSpec(
      label: 'Nord',
      caption: 'Arctic, restrained, cool',
      accent: Color(0xFF88C0D0),
      accentSecondary: Color(0xFF81A1C1),
      canvas: Color(0xFF1E222B),
      panel: Color(0xFF272C36),
      panelElevated: Color(0xFF2E3440),
      hairline: Color(0xFF3B4252),
      border: Color(0xFF434C5E),
      foreground: Color(0xFFE5E9F0),
      mutedForeground: Color(0xFFA8B0BF),
      subtleForeground: Color(0xFF4C566A),
      success: Color(0xFFA3BE8C),
      warning: Color(0xFFEBCB8B),
      danger: Color(0xFFBF616A),
      canvasLight: Color(0xFFECEFF4),
      foregroundLight: Color(0xFF2E3440),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFD8DEE9),
        selection: Color(0x664C566A),
        foreground: Color(0xFFE5E9F0),
        background: Color(0xFF1E222B),
        black: Color(0xFF3B4252),
        red: Color(0xFFBF616A),
        green: Color(0xFFA3BE8C),
        yellow: Color(0xFFEBCB8B),
        blue: Color(0xFF81A1C1),
        magenta: Color(0xFFB48EAD),
        cyan: Color(0xFF88C0D0),
        white: Color(0xFFE5E9F0),
        brightBlack: Color(0xFF4C566A),
        brightRed: Color(0xFFBF616A),
        brightGreen: Color(0xFFA3BE8C),
        brightYellow: Color(0xFFEBCB8B),
        brightBlue: Color(0xFF81A1C1),
        brightMagenta: Color(0xFFB48EAD),
        brightCyan: Color(0xFF8FBCBB),
        brightWhite: Color(0xFFECEFF4),
        searchHitBackground: Color(0xFFEBCB8B),
        searchHitBackgroundCurrent: Color(0xFF88C0D0),
        searchHitForeground: Color(0xFF1E222B),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF2E3440),
        selection: Color(0x66D8DEE9),
        foreground: Color(0xFF2E3440),
        background: Color(0xFFECEFF4),
        black: Color(0xFF3B4252),
        red: Color(0xFFBF616A),
        green: Color(0xFF4F7A37),
        yellow: Color(0xFFB48B37),
        blue: Color(0xFF5E81AC),
        magenta: Color(0xFF8F5E84),
        cyan: Color(0xFF548E9B),
        white: Color(0xFFD8DEE9),
        brightBlack: Color(0xFF4C566A),
        brightRed: Color(0xFFBF616A),
        brightGreen: Color(0xFF4F7A37),
        brightYellow: Color(0xFFB48B37),
        brightBlue: Color(0xFF5E81AC),
        brightMagenta: Color(0xFF8F5E84),
        brightCyan: Color(0xFF548E9B),
        brightWhite: Color(0xFF2E3440),
        searchHitBackground: Color(0xFFEBCB8B),
        searchHitBackgroundCurrent: Color(0xFF88C0D0),
        searchHitForeground: Color(0xFF2E3440),
      ),
    ),
    AppPalette.gruvbox => const PaletteSpec(
      label: 'Gruvbox',
      caption: 'Warm retro terminal energy',
      accent: Color(0xFFD79921),
      accentSecondary: Color(0xFFB16286),
      canvas: Color(0xFF1A1B1B),
      panel: Color(0xFF24262A),
      panelElevated: Color(0xFF2C2F33),
      hairline: Color(0xFF332F2C),
      border: Color(0xFF3C3836),
      foreground: Color(0xFFEBDBB2),
      mutedForeground: Color(0xFFA89984),
      subtleForeground: Color(0xFF7C6F64),
      success: Color(0xFFB8BB26),
      warning: Color(0xFFFABD2F),
      danger: Color(0xFFFB4934),
      canvasLight: Color(0xFFFBF1C7),
      foregroundLight: Color(0xFF3C3836),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFEBDBB2),
        selection: Color(0x66504945),
        foreground: Color(0xFFEBDBB2),
        background: Color(0xFF1A1B1B),
        black: Color(0xFF282828),
        red: Color(0xFFCC241D),
        green: Color(0xFF98971A),
        yellow: Color(0xFFD79921),
        blue: Color(0xFF458588),
        magenta: Color(0xFFB16286),
        cyan: Color(0xFF689D6A),
        white: Color(0xFFA89984),
        brightBlack: Color(0xFF928374),
        brightRed: Color(0xFFFB4934),
        brightGreen: Color(0xFFB8BB26),
        brightYellow: Color(0xFFFABD2F),
        brightBlue: Color(0xFF83A598),
        brightMagenta: Color(0xFFD3869B),
        brightCyan: Color(0xFF8EC07C),
        brightWhite: Color(0xFFEBDBB2),
        searchHitBackground: Color(0xFFD79921),
        searchHitBackgroundCurrent: Color(0xFF98971A),
        searchHitForeground: Color(0xFF1A1B1B),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF3C3836),
        selection: Color(0x66D5C4A1),
        foreground: Color(0xFF3C3836),
        background: Color(0xFFFBF1C7),
        black: Color(0xFF7C6F64),
        red: Color(0xFFCC241D),
        green: Color(0xFF79740E),
        yellow: Color(0xFFB57614),
        blue: Color(0xFF076678),
        magenta: Color(0xFF8F3F71),
        cyan: Color(0xFF427B58),
        white: Color(0xFFD5C4A1),
        brightBlack: Color(0xFF928374),
        brightRed: Color(0xFF9D0006),
        brightGreen: Color(0xFF79740E),
        brightYellow: Color(0xFFB57614),
        brightBlue: Color(0xFF076678),
        brightMagenta: Color(0xFF8F3F71),
        brightCyan: Color(0xFF427B58),
        brightWhite: Color(0xFF3C3836),
        searchHitBackground: Color(0xFFD79921),
        searchHitBackgroundCurrent: Color(0xFF98971A),
        searchHitForeground: Color(0xFFFBF1C7),
      ),
    ),
    AppPalette.solarized => const PaletteSpec(
      label: 'Solarized',
      caption: 'Balanced low-glare contrast',
      accent: Color(0xFF268BD2),
      accentSecondary: Color(0xFFD33682),
      canvas: Color(0xFF002731),
      panel: Color(0xFF073642),
      panelElevated: Color(0xFF0B3D49),
      hairline: Color(0xFF124854),
      border: Color(0xFF195563),
      foreground: Color(0xFFEEE8D5),
      mutedForeground: Color(0xFF93A1A1),
      subtleForeground: Color(0xFF586E75),
      success: Color(0xFF859900),
      warning: Color(0xFFB58900),
      danger: Color(0xFFDC322F),
      canvasLight: Color(0xFFFDF6E3),
      foregroundLight: Color(0xFF073642),
      terminalDark: TerminalTheme(
        cursor: Color(0xFF93A1A1),
        selection: Color(0x66586E75),
        foreground: Color(0xFFEEE8D5),
        background: Color(0xFF002731),
        black: Color(0xFF073642),
        red: Color(0xFFDC322F),
        green: Color(0xFF859900),
        yellow: Color(0xFFB58900),
        blue: Color(0xFF268BD2),
        magenta: Color(0xFFD33682),
        cyan: Color(0xFF2AA198),
        white: Color(0xFFEEE8D5),
        brightBlack: Color(0xFF586E75),
        brightRed: Color(0xFFCB4B16),
        brightGreen: Color(0xFF586E75),
        brightYellow: Color(0xFF657B83),
        brightBlue: Color(0xFF839496),
        brightMagenta: Color(0xFF6C71C4),
        brightCyan: Color(0xFF93A1A1),
        brightWhite: Color(0xFFFDF6E3),
        searchHitBackground: Color(0xFFB58900),
        searchHitBackgroundCurrent: Color(0xFF268BD2),
        searchHitForeground: Color(0xFF002731),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF586E75),
        selection: Color(0x66EEE8D5),
        foreground: Color(0xFF586E75),
        background: Color(0xFFFDF6E3),
        black: Color(0xFF073642),
        red: Color(0xFFDC322F),
        green: Color(0xFF859900),
        yellow: Color(0xFFB58900),
        blue: Color(0xFF268BD2),
        magenta: Color(0xFFD33682),
        cyan: Color(0xFF2AA198),
        white: Color(0xFFEEE8D5),
        brightBlack: Color(0xFF002B36),
        brightRed: Color(0xFFCB4B16),
        brightGreen: Color(0xFF586E75),
        brightYellow: Color(0xFF657B83),
        brightBlue: Color(0xFF839496),
        brightMagenta: Color(0xFF6C71C4),
        brightCyan: Color(0xFF93A1A1),
        brightWhite: Color(0xFFFDF6E3),
        searchHitBackground: Color(0xFFB58900),
        searchHitBackgroundCurrent: Color(0xFF268BD2),
        searchHitForeground: Color(0xFFFDF6E3),
      ),
    ),
    AppPalette.oneDark => const PaletteSpec(
      label: 'One Dark',
      caption: 'Atom-inspired editor calm',
      accent: Color(0xFF61AFEF),
      accentSecondary: Color(0xFFC678DD),
      canvas: Color(0xFF181A20),
      panel: Color(0xFF21252B),
      panelElevated: Color(0xFF282C34),
      hairline: Color(0xFF353B45),
      border: Color(0xFF3E4451),
      foreground: Color(0xFFABB2BF),
      mutedForeground: Color(0xFF828997),
      subtleForeground: Color(0xFF5C6370),
      success: Color(0xFF98C379),
      warning: Color(0xFFE5C07B),
      danger: Color(0xFFE06C75),
      canvasLight: Color(0xFFECEFF4),
      foregroundLight: Color(0xFF282C34),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFABB2BF),
        selection: Color(0x665C6370),
        foreground: Color(0xFFABB2BF),
        background: Color(0xFF181A20),
        black: Color(0xFF282C34),
        red: Color(0xFFE06C75),
        green: Color(0xFF98C379),
        yellow: Color(0xFFE5C07B),
        blue: Color(0xFF61AFEF),
        magenta: Color(0xFFC678DD),
        cyan: Color(0xFF56B6C2),
        white: Color(0xFFABB2BF),
        brightBlack: Color(0xFF5C6370),
        brightRed: Color(0xFFE06C75),
        brightGreen: Color(0xFF98C379),
        brightYellow: Color(0xFFE5C07B),
        brightBlue: Color(0xFF61AFEF),
        brightMagenta: Color(0xFFC678DD),
        brightCyan: Color(0xFF56B6C2),
        brightWhite: Color(0xFFC8CCD4),
        searchHitBackground: Color(0xFFE5C07B),
        searchHitBackgroundCurrent: Color(0xFF61AFEF),
        searchHitForeground: Color(0xFF181A20),
      ),
      terminalLight: _lightFallbackTerminal,
    ),
    AppPalette.rosePine => const PaletteSpec(
      label: 'Rosé Pine',
      caption: 'Muted dusk, soft contrast',
      accent: Color(0xFFC4A7E7),
      accentSecondary: Color(0xFFEBBCBA),
      canvas: Color(0xFF191724),
      panel: Color(0xFF1F1D2E),
      panelElevated: Color(0xFF26233A),
      hairline: Color(0xFF403D52),
      border: Color(0xFF524F67),
      foreground: Color(0xFFE0DEF4),
      mutedForeground: Color(0xFF908CAA),
      subtleForeground: Color(0xFF6E6A86),
      success: Color(0xFF9CCFD8),
      warning: Color(0xFFF6C177),
      danger: Color(0xFFEB6F92),
      canvasLight: Color(0xFFFFFAF3),
      foregroundLight: Color(0xFF191724),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFE0DEF4),
        selection: Color(0x66524F67),
        foreground: Color(0xFFE0DEF4),
        background: Color(0xFF191724),
        black: Color(0xFF26233A),
        red: Color(0xFFEB6F92),
        green: Color(0xFF9CCFD8),
        yellow: Color(0xFFF6C177),
        blue: Color(0xFF31748F),
        magenta: Color(0xFFC4A7E7),
        cyan: Color(0xFFEBBCBA),
        white: Color(0xFFE0DEF4),
        brightBlack: Color(0xFF6E6A86),
        brightRed: Color(0xFFEB6F92),
        brightGreen: Color(0xFF9CCFD8),
        brightYellow: Color(0xFFF6C177),
        brightBlue: Color(0xFF31748F),
        brightMagenta: Color(0xFFC4A7E7),
        brightCyan: Color(0xFFEBBCBA),
        brightWhite: Color(0xFFE0DEF4),
        searchHitBackground: Color(0xFFF6C177),
        searchHitBackgroundCurrent: Color(0xFFC4A7E7),
        searchHitForeground: Color(0xFF191724),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF575279),
        selection: Color(0x66DFDAD9),
        foreground: Color(0xFF575279),
        background: Color(0xFFFFFAF3),
        black: Color(0xFF797593),
        red: Color(0xFFB4637A),
        green: Color(0xFF286983),
        yellow: Color(0xFFEA9D34),
        blue: Color(0xFF56949F),
        magenta: Color(0xFF907AA9),
        cyan: Color(0xFFD7827E),
        white: Color(0xFFDFDAD9),
        brightBlack: Color(0xFF9893A5),
        brightRed: Color(0xFFB4637A),
        brightGreen: Color(0xFF286983),
        brightYellow: Color(0xFFEA9D34),
        brightBlue: Color(0xFF56949F),
        brightMagenta: Color(0xFF907AA9),
        brightCyan: Color(0xFFD7827E),
        brightWhite: Color(0xFF575279),
        searchHitBackground: Color(0xFFF6C177),
        searchHitBackgroundCurrent: Color(0xFFC4A7E7),
        searchHitForeground: Color(0xFFFFFAF3),
      ),
    ),
    AppPalette.everforest => const PaletteSpec(
      label: 'Everforest',
      caption: 'Green low-glare woodland',
      accent: Color(0xFFA7C080),
      accentSecondary: Color(0xFFE67E80),
      canvas: Color(0xFF1E2326),
      panel: Color(0xFF272E33),
      panelElevated: Color(0xFF2E383C),
      hairline: Color(0xFF3A464C),
      border: Color(0xFF4F5B58),
      foreground: Color(0xFFD3C6AA),
      mutedForeground: Color(0xFF9DA9A0),
      subtleForeground: Color(0xFF859289),
      success: Color(0xFFA7C080),
      warning: Color(0xFFDBBC7F),
      danger: Color(0xFFE67E80),
      canvasLight: Color(0xFFFDF6E3),
      foregroundLight: Color(0xFF3A464C),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFD3C6AA),
        selection: Color(0x66543A48),
        foreground: Color(0xFFD3C6AA),
        background: Color(0xFF1E2326),
        black: Color(0xFF272E33),
        red: Color(0xFFE67E80),
        green: Color(0xFFA7C080),
        yellow: Color(0xFFDBBC7F),
        blue: Color(0xFF7FBBB3),
        magenta: Color(0xFFD699B6),
        cyan: Color(0xFF83C092),
        white: Color(0xFFD3C6AA),
        brightBlack: Color(0xFF859289),
        brightRed: Color(0xFFE67E80),
        brightGreen: Color(0xFFA7C080),
        brightYellow: Color(0xFFDBBC7F),
        brightBlue: Color(0xFF7FBBB3),
        brightMagenta: Color(0xFFD699B6),
        brightCyan: Color(0xFF83C092),
        brightWhite: Color(0xFFD3C6AA),
        searchHitBackground: Color(0xFFDBBC7F),
        searchHitBackgroundCurrent: Color(0xFFA7C080),
        searchHitForeground: Color(0xFF1E2326),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF5C6A72),
        selection: Color(0x66D8D3BA),
        foreground: Color(0xFF5C6A72),
        background: Color(0xFFFDF6E3),
        black: Color(0xFF5C6A72),
        red: Color(0xFFF85552),
        green: Color(0xFF8DA101),
        yellow: Color(0xFFDFA000),
        blue: Color(0xFF3A94C5),
        magenta: Color(0xFFDF69BA),
        cyan: Color(0xFF35A77C),
        white: Color(0xFFD8D3BA),
        brightBlack: Color(0xFF829181),
        brightRed: Color(0xFFF85552),
        brightGreen: Color(0xFF8DA101),
        brightYellow: Color(0xFFDFA000),
        brightBlue: Color(0xFF3A94C5),
        brightMagenta: Color(0xFFDF69BA),
        brightCyan: Color(0xFF35A77C),
        brightWhite: Color(0xFF5C6A72),
        searchHitBackground: Color(0xFFDBBC7F),
        searchHitBackgroundCurrent: Color(0xFFA7C080),
        searchHitForeground: Color(0xFFFDF6E3),
      ),
    ),
    AppPalette.monokai => const PaletteSpec(
      label: 'Monokai',
      caption: 'Punchy classic code color',
      accent: Color(0xFFA6E22E),
      accentSecondary: Color(0xFFF92672),
      canvas: Color(0xFF1B1C1A),
      panel: Color(0xFF272822),
      panelElevated: Color(0xFF2D2E29),
      hairline: Color(0xFF3A3B35),
      border: Color(0xFF49483E),
      foreground: Color(0xFFF8F8F2),
      mutedForeground: Color(0xFFCFCFC2),
      subtleForeground: Color(0xFF75715E),
      success: Color(0xFFA6E22E),
      warning: Color(0xFFE6DB74),
      danger: Color(0xFFF92672),
      canvasLight: Color(0xFFF7F7EF),
      foregroundLight: Color(0xFF272822),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFF8F8F2),
        selection: Color(0x6649435C),
        foreground: Color(0xFFF8F8F2),
        background: Color(0xFF1B1C1A),
        black: Color(0xFF272822),
        red: Color(0xFFF92672),
        green: Color(0xFFA6E22E),
        yellow: Color(0xFFE6DB74),
        blue: Color(0xFF66D9EF),
        magenta: Color(0xFFAE81FF),
        cyan: Color(0xFFA1EFE4),
        white: Color(0xFFF8F8F2),
        brightBlack: Color(0xFF75715E),
        brightRed: Color(0xFFF92672),
        brightGreen: Color(0xFFA6E22E),
        brightYellow: Color(0xFFE6DB74),
        brightBlue: Color(0xFF66D9EF),
        brightMagenta: Color(0xFFAE81FF),
        brightCyan: Color(0xFFA1EFE4),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFE6DB74),
        searchHitBackgroundCurrent: Color(0xFFA6E22E),
        searchHitForeground: Color(0xFF1B1C1A),
      ),
      terminalLight: TerminalTheme(
        cursor: Color(0xFF272822),
        selection: Color(0x66D7D7C7),
        foreground: Color(0xFF272822),
        background: Color(0xFFF7F7EF),
        black: Color(0xFF49483E),
        red: Color(0xFFF92672),
        green: Color(0xFF669900),
        yellow: Color(0xFFC4A000),
        blue: Color(0xFF4477AA),
        magenta: Color(0xFF9E6FFE),
        cyan: Color(0xFF1F9EAA),
        white: Color(0xFFD7D7C7),
        brightBlack: Color(0xFF75715E),
        brightRed: Color(0xFFF92672),
        brightGreen: Color(0xFF669900),
        brightYellow: Color(0xFFC4A000),
        brightBlue: Color(0xFF4477AA),
        brightMagenta: Color(0xFF9E6FFE),
        brightCyan: Color(0xFF1F9EAA),
        brightWhite: Color(0xFF272822),
        searchHitBackground: Color(0xFFE6DB74),
        searchHitBackgroundCurrent: Color(0xFFA6E22E),
        searchHitForeground: Color(0xFFF7F7EF),
      ),
    ),
    AppPalette.ayuDark => const PaletteSpec(
      label: 'Ayu Dark',
      caption: 'Warm amber night coding',
      accent: Color(0xFFFFB454),
      accentSecondary: Color(0xFFFF8F40),
      canvas: Color(0xFF0B0E14),
      panel: Color(0xFF11151C),
      panelElevated: Color(0xFF191E2A),
      hairline: Color(0xFF242C3A),
      border: Color(0xFF334155),
      foreground: Color(0xFFB3B1AD),
      mutedForeground: Color(0xFF828C99),
      subtleForeground: Color(0xFF5C6773),
      success: Color(0xFFC2D94C),
      warning: Color(0xFFFFB454),
      danger: Color(0xFFFF3333),
      canvasLight: Color(0xFFFFF8E7),
      foregroundLight: Color(0xFF191E2A),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFE6B673),
        selection: Color(0x66409FFF),
        foreground: Color(0xFFB3B1AD),
        background: Color(0xFF0B0E14),
        black: Color(0xFF01060E),
        red: Color(0xFFFF3333),
        green: Color(0xFFC2D94C),
        yellow: Color(0xFFFFB454),
        blue: Color(0xFF59C2FF),
        magenta: Color(0xFFFF8F40),
        cyan: Color(0xFF95E6CB),
        white: Color(0xFFB3B1AD),
        brightBlack: Color(0xFF5C6773),
        brightRed: Color(0xFFFF3333),
        brightGreen: Color(0xFFC2D94C),
        brightYellow: Color(0xFFFFB454),
        brightBlue: Color(0xFF59C2FF),
        brightMagenta: Color(0xFFFF8F40),
        brightCyan: Color(0xFF95E6CB),
        brightWhite: Color(0xFFE6E1CF),
        searchHitBackground: Color(0xFFFFB454),
        searchHitBackgroundCurrent: Color(0xFF59C2FF),
        searchHitForeground: Color(0xFF0B0E14),
      ),
      terminalLight: _lightFallbackTerminal,
    ),
    AppPalette.kanagawa => const PaletteSpec(
      label: 'Kanagawa',
      caption: 'Muted ink and wave tones',
      accent: Color(0xFF7E9CD8),
      accentSecondary: Color(0xFFC8C093),
      canvas: Color(0xFF16161D),
      panel: Color(0xFF1F1F28),
      panelElevated: Color(0xFF252535),
      hairline: Color(0xFF363646),
      border: Color(0xFF54546D),
      foreground: Color(0xFFDCD7BA),
      mutedForeground: Color(0xFF9CABCA),
      subtleForeground: Color(0xFF727169),
      success: Color(0xFF98BB6C),
      warning: Color(0xFFE6C384),
      danger: Color(0xFFC34043),
      canvasLight: Color(0xFFF2ECBC),
      foregroundLight: Color(0xFF1F1F28),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFDCD7BA),
        selection: Color(0x6654546D),
        foreground: Color(0xFFDCD7BA),
        background: Color(0xFF16161D),
        black: Color(0xFF1F1F28),
        red: Color(0xFFC34043),
        green: Color(0xFF76946A),
        yellow: Color(0xFFC0A36E),
        blue: Color(0xFF7E9CD8),
        magenta: Color(0xFF957FB8),
        cyan: Color(0xFF6A9589),
        white: Color(0xFFC8C093),
        brightBlack: Color(0xFF727169),
        brightRed: Color(0xFFE82424),
        brightGreen: Color(0xFF98BB6C),
        brightYellow: Color(0xFFE6C384),
        brightBlue: Color(0xFF7FB4CA),
        brightMagenta: Color(0xFF938AA9),
        brightCyan: Color(0xFF7AA89F),
        brightWhite: Color(0xFFDCD7BA),
        searchHitBackground: Color(0xFFE6C384),
        searchHitBackgroundCurrent: Color(0xFF7E9CD8),
        searchHitForeground: Color(0xFF16161D),
      ),
      terminalLight: _lightFallbackTerminal,
    ),
    AppPalette.nightOwl => const PaletteSpec(
      label: 'Night Owl',
      caption: 'Crisp blue late-night focus',
      accent: Color(0xFF82AAFF),
      accentSecondary: Color(0xFFC792EA),
      canvas: Color(0xFF011627),
      panel: Color(0xFF071D2F),
      panelElevated: Color(0xFF0B2942),
      hairline: Color(0xFF12344D),
      border: Color(0xFF1D4A66),
      foreground: Color(0xFFD6DEEB),
      mutedForeground: Color(0xFF7E9DB5),
      subtleForeground: Color(0xFF637E99),
      success: Color(0xFF22DA6E),
      warning: Color(0xFFFFEB95),
      danger: Color(0xFFEF5350),
      canvasLight: Color(0xFFEAF4FF),
      foregroundLight: Color(0xFF011627),
      terminalDark: TerminalTheme(
        cursor: Color(0xFF80A4C2),
        selection: Color(0x664B6479),
        foreground: Color(0xFFD6DEEB),
        background: Color(0xFF011627),
        black: Color(0xFF011627),
        red: Color(0xFFEF5350),
        green: Color(0xFF22DA6E),
        yellow: Color(0xFFFFEB95),
        blue: Color(0xFF82AAFF),
        magenta: Color(0xFFC792EA),
        cyan: Color(0xFF21C7A8),
        white: Color(0xFFD6DEEB),
        brightBlack: Color(0xFF575656),
        brightRed: Color(0xFFEF5350),
        brightGreen: Color(0xFF22DA6E),
        brightYellow: Color(0xFFFFEB95),
        brightBlue: Color(0xFF82AAFF),
        brightMagenta: Color(0xFFC792EA),
        brightCyan: Color(0xFF7FDBCA),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFFFEB95),
        searchHitBackgroundCurrent: Color(0xFF82AAFF),
        searchHitForeground: Color(0xFF011627),
      ),
      terminalLight: _lightFallbackTerminal,
    ),
    AppPalette.palenight => const PaletteSpec(
      label: 'Palenight',
      caption: 'Soft violet editor glow',
      accent: Color(0xFFC792EA),
      accentSecondary: Color(0xFF89DDFF),
      canvas: Color(0xFF202331),
      panel: Color(0xFF292D3E),
      panelElevated: Color(0xFF34394F),
      hairline: Color(0xFF3D435E),
      border: Color(0xFF4B5274),
      foreground: Color(0xFFA6ACCD),
      mutedForeground: Color(0xFF828BB8),
      subtleForeground: Color(0xFF676E95),
      success: Color(0xFFC3E88D),
      warning: Color(0xFFFFCB6B),
      danger: Color(0xFFF07178),
      canvasLight: Color(0xFFF2F0FF),
      foregroundLight: Color(0xFF292D3E),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFFFCC00),
        selection: Color(0x66444A73),
        foreground: Color(0xFFA6ACCD),
        background: Color(0xFF202331),
        black: Color(0xFF292D3E),
        red: Color(0xFFF07178),
        green: Color(0xFFC3E88D),
        yellow: Color(0xFFFFCB6B),
        blue: Color(0xFF82AAFF),
        magenta: Color(0xFFC792EA),
        cyan: Color(0xFF89DDFF),
        white: Color(0xFFA6ACCD),
        brightBlack: Color(0xFF676E95),
        brightRed: Color(0xFFFF8B92),
        brightGreen: Color(0xFFDDFFA7),
        brightYellow: Color(0xFFFFE585),
        brightBlue: Color(0xFF9CC4FF),
        brightMagenta: Color(0xFFE1ACFF),
        brightCyan: Color(0xFFA3F7FF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFFFCB6B),
        searchHitBackgroundCurrent: Color(0xFFC792EA),
        searchHitForeground: Color(0xFF202331),
      ),
      terminalLight: _lightFallbackTerminal,
    ),
    AppPalette.synthwave => const PaletteSpec(
      label: 'Synthwave',
      caption: 'Electric retro terminal pop',
      accent: Color(0xFFFF7EDB),
      accentSecondary: Color(0xFF36F9F6),
      canvas: Color(0xFF191528),
      panel: Color(0xFF241B3D),
      panelElevated: Color(0xFF2D2350),
      hairline: Color(0xFF3B2D67),
      border: Color(0xFF4A3A7A),
      foreground: Color(0xFFF4F4F7),
      mutedForeground: Color(0xFFC9B7FF),
      subtleForeground: Color(0xFF8B7EC8),
      success: Color(0xFF72F1B8),
      warning: Color(0xFFFFD866),
      danger: Color(0xFFFF5370),
      canvasLight: Color(0xFFFFF0FB),
      foregroundLight: Color(0xFF241B3D),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFFF7EDB),
        selection: Color(0x665A3D8E),
        foreground: Color(0xFFF4F4F7),
        background: Color(0xFF191528),
        black: Color(0xFF241B3D),
        red: Color(0xFFFF5370),
        green: Color(0xFF72F1B8),
        yellow: Color(0xFFFFD866),
        blue: Color(0xFF36F9F6),
        magenta: Color(0xFFFF7EDB),
        cyan: Color(0xFFFEDE5D),
        white: Color(0xFFF4F4F7),
        brightBlack: Color(0xFF8B7EC8),
        brightRed: Color(0xFFFF5370),
        brightGreen: Color(0xFF72F1B8),
        brightYellow: Color(0xFFFFD866),
        brightBlue: Color(0xFF36F9F6),
        brightMagenta: Color(0xFFFF7EDB),
        brightCyan: Color(0xFFFEDE5D),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFFFD866),
        searchHitBackgroundCurrent: Color(0xFFFF7EDB),
        searchHitForeground: Color(0xFF191528),
      ),
      terminalLight: _lightFallbackTerminal,
    ),
    AppPalette.githubDark => const PaletteSpec(
      label: 'GitHub Dark',
      caption: 'Quiet modern code contrast',
      accent: Color(0xFF58A6FF),
      accentSecondary: Color(0xFFBC8CFF),
      canvas: Color(0xFF0D1117),
      panel: Color(0xFF161B22),
      panelElevated: Color(0xFF21262D),
      hairline: Color(0xFF30363D),
      border: Color(0xFF3B434D),
      foreground: Color(0xFFC9D1D9),
      mutedForeground: Color(0xFF8B949E),
      subtleForeground: Color(0xFF6E7681),
      success: Color(0xFF3FB950),
      warning: Color(0xFFD29922),
      danger: Color(0xFFF85149),
      canvasLight: Color(0xFFF0F3F6),
      foregroundLight: Color(0xFF24292F),
      terminalDark: TerminalTheme(
        cursor: Color(0xFFC9D1D9),
        selection: Color(0x66388BFD),
        foreground: Color(0xFFC9D1D9),
        background: Color(0xFF0D1117),
        black: Color(0xFF161B22),
        red: Color(0xFFFF7B72),
        green: Color(0xFF3FB950),
        yellow: Color(0xFFD29922),
        blue: Color(0xFF58A6FF),
        magenta: Color(0xFFBC8CFF),
        cyan: Color(0xFF39C5CF),
        white: Color(0xFFC9D1D9),
        brightBlack: Color(0xFF6E7681),
        brightRed: Color(0xFFFF7B72),
        brightGreen: Color(0xFF3FB950),
        brightYellow: Color(0xFFD29922),
        brightBlue: Color(0xFF58A6FF),
        brightMagenta: Color(0xFFBC8CFF),
        brightCyan: Color(0xFF39C5CF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFD29922),
        searchHitBackgroundCurrent: Color(0xFF58A6FF),
        searchHitForeground: Color(0xFF0D1117),
      ),
      terminalLight: _lightFallbackTerminal,
    ),
  };
}
